USE WAREHOUSE AWWarehouse;
USE DATABASE AWDatabase;
USE SCHEMA AWSchema;
USE STAGE AWStage ;

COPY INTO OrderDetails
FROM @awstage/AdventureWorks_Sales_2015.csv.gz
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO OrderDetails
FROM @awstage/AdventureWorks_Sales_2016.csv.gz
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO OrderDetails
FROM @awstage/AdventureWorks_Sales_2017.csv.gz
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';



COPY INTO Customer
FROM @AWStage/AdventureWorks_Customers.csv.gz
file_format = (type = csv field_delimiter = ',' skip_header = 1)
ON_ERROR = 'continue';

COPY INTO SalesTerritory
FROM @awstage/AdventureWorks_Territories.csv.gz
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO Product
FROM @awstage/AdventureWorks_Products.csv.gz
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO ProductSubcategory
FROM @awstage/AdventureWorks_Product_Subcategories.csv.gz
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

COPY INTO ProductCategory
FROM @awstage/AdventureWorks_Product_Categories.csv.gz
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';