USE WAREHOUSE AWWarehouse;
USE DATABASE AWDatabase;
USE SCHEMA AWSchema;
USE STAGE AWStage ;

CREATE OR REPLACE PIPE AdventureWorksALL AS 
COPY INTO AWDatabase.AWSchema.AWMergedData
FROM @AWDatabase.AWSchema.AWStage
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = ',' SKIP_HEADER = 1)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TASK RefreshPipe
WAREHOUSE = AWWAREHOUSE 
SCHEDULE = 'USING CRON 0 * * * * UTC' 
AS
ALTER PIPE AdventureWorksALL REFRESH;

